// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPd6b14ReKXGw08fc51Nl8wfiaJZ_jRE',
    appId: '1:85578438685:web:01e14dbaf9641395988ef4',
    messagingSenderId: '85578438685',
    projectId: 'quiz-ace9a',
    authDomain: 'quiz-ace9a.firebaseapp.com',
    storageBucket: 'quiz-ace9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC18uh-Tq_trE7citTe0baJUybZ202RHzs',
    appId: '1:85578438685:android:a24df1f4028cc1eb988ef4',
    messagingSenderId: '85578438685',
    projectId: 'quiz-ace9a',
    storageBucket: 'quiz-ace9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmyliwzsxEBdUddxZvpFZu8tbYyDQFyE',
    appId: '1:85578438685:ios:6d6b389705daa022988ef4',
    messagingSenderId: '85578438685',
    projectId: 'quiz-ace9a',
    storageBucket: 'quiz-ace9a.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
